### ISSUE TITLE
Confused on setup

### ISSUE THREAD

**Issue by Starwarsgaming** [walksanatora/aeiou-mc#2]
I'm quite literally just confused on what any of this means, how do I put on path? what does this even mean? I'm sorry for the uneducated questions I just cant find answers anywhere.

**Comment by walksanatora** [comment]
so first you need to download [dectalk](https://github.com/dectalk/dectalk/releases) from their releases (probally wanna get vs6.zip on windows)
then you need to place at $HOME/.tts  on windows this would be the same as `C:\Users\<your user>\.tts`
extract the contents of that to the above folder
rename `say.exe` to `dectalk.exe`

if you want SAM to be native you would have to compile it yourself... I do not know how to cross-compile it for windows
(luckily though it is allready included via the power of WebAssembly)

and it isn't your fault working with PATH can be daunting for new people (PATH is a system used by windows and linux and mac to locate programs)
